name: dwello
description: A mobile platform for structured relocation services in Ghana

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  
  # State Management
  provider: ^6.1.1
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  
  # Utilities
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  url_launcher: ^6.2.2
  intl: ^0.19.0
  uuid: ^4.2.1
  cached_network_image: ^3.3.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  
  # File handling
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  
  # HTTP & Networking
  http: ^1.1.2
  
  # Rating
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700