// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemo_WebApiKey_Replace_With_Real_Key',
    appId: '1:123456789:web:demo_web_app_id',
    messagingSenderId: '123456789',
    projectId: 'dwello-demo-project',
    authDomain: 'dwello-demo-project.firebaseapp.com',
    storageBucket: 'dwello-demo-project.appspot.com',
    measurementId: 'G-DEMO_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemo_AndroidApiKey_Replace_With_Real_Key',
    appId: '1:123456789:android:demo_android_app_id',
    messagingSenderId: '123456789',
    projectId: 'dwello-demo-project',
    storageBucket: 'dwello-demo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemo_iOSApiKey_Replace_With_Real_Key',
    appId: '1:123456789:ios:demo_ios_app_id',
    messagingSenderId: '123456789',
    projectId: 'dwello-demo-project',
    storageBucket: 'dwello-demo-project.appspot.com',
    iosBundleId: 'com.example.dwelloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemo_macOSApiKey_Replace_With_Real_Key',
    appId: '1:123456789:macos:demo_macos_app_id',
    messagingSenderId: '123456789',
    projectId: 'dwello-demo-project',
    storageBucket: 'dwello-demo-project.appspot.com',
    iosBundleId: 'com.example.dwelloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemo_WindowsApiKey_Replace_With_Real_Key',
    appId: '1:123456789:windows:demo_windows_app_id',
    messagingSenderId: '123456789',
    projectId: 'dwello-demo-project',
    authDomain: 'dwello-demo-project.firebaseapp.com',
    storageBucket: 'dwello-demo-project.appspot.com',
    measurementId: 'G-DEMO_MEASUREMENT_ID',
  );
}